In [1]:
import re
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import patsy
import statsmodels.api as sm
import seaborn as sns
%matplotlib notebook

In [46]:
data = pd.read_csv('winemag-data-130k-v2.csv')
data

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [3]:
country = data['country'].unique()

In [27]:
avg = []
for i in country:
    avg.append(data[data.country == i]['points'].mean())

In [28]:
avg_points = {'Country':country, 'Average Points': avg} 

avg_points = pd.DataFrame(avg_points) 
 
avg_points = avg_points.sort_values(by=['Average Points'], ascending=False)
avg_points

                   Country  Average Points
26                 England       91.581081
33                   India       90.222222
9                  Austria       90.101345
5                  Germany       89.851732
17                  Canada       89.369650
13                 Hungary       89.191781
42                   China       89.000000
4                   France       88.845109
22              Luxembourg       88.666667
8                Australia       88.580507
37             Switzerland       88.571429
31                 Morocco       88.571429
2                       US       88.563720
0                    Italy       88.562231
12                  Israel       88.471287
11             New Zealand       88.303030
1                 Portugal       88.250220
19                  Turkey       88.088889
21                Slovenia       88.068966
10            South Africa       88.056388
34                Bulgaria       87.936170
24                 Georgia       87.686047
27                 Lebanon       87.685714
28                  Serbia       87.500000
36                 Armenia       87.500000
3                    Spain       87.288337
14                  Greece       87.283262
20          Czech Republic       87.250000
23                 Croatia       87.219178
30                 Moldova       87.203390
35                  Cyprus       87.181818
40                Slovakia       87.000000
41               Macedonia       86.833333
25                 Uruguay       86.752294
6                Argentina       86.710263
38  Bosnia and Herzegovina       86.500000
7                    Chile       86.493515
15                 Romania       86.400000
16                  Mexico       85.257143
29                  Brazil       84.673077
39                 Ukraine       84.071429
43                   Egypt       84.000000
32                    Peru       83.562500
18                     NaN             NaN

In [6]:
winery = data['winery'].unique()
winery

array(['Nicosia', 'Quinta dos Avidagos', 'Rainstorm', ...,
       'Mas de Pampelonne', 'Bodegas Eidosela', 'Penedo Borges'],
      dtype=object)

In [7]:
avg1 = []
for i in winery:
    avg1.append(data[data.winery == i]['points'].mean())

In [8]:
wavg_points = {'Winery':winery, 'Average Points': avg1} 

wavg_points = pd.DataFrame(wavg_points) 
 
wavg_points = wavg_points.sort_values(by=['Average Points'], ascending=False)
wavg_points

                   Winery  Average Points
11466              Araujo            98.0
16486             Gandona            97.0
16485                Ovid            97.0
15600          J.L. Chave            97.0
7914                Salon            96.8
...                   ...             ...
16310        Gran Familia            80.0
7130           Villa Viña            80.0
16334        Capay Valley            80.0
14868           Moss Roxx            80.0
8075   California's Jewel            80.0

[16757 rows x 2 columns]

In [12]:
grapes = data['variety'].unique()
grapes

array(['White Blend', 'Portuguese Red', 'Pinot Gris', 'Riesling',
       'Pinot Noir', 'Tempranillo-Merlot', 'Frappato', 'Gewürztraminer',
       'Cabernet Sauvignon', 'Nerello Mascalese', 'Chardonnay', 'Malbec',
       'Tempranillo Blend', 'Meritage', 'Red Blend', 'Merlot',
       "Nero d'Avola", 'Chenin Blanc', 'Gamay', 'Sauvignon Blanc',
       'Viognier-Chardonnay', 'Primitivo', 'Catarratto', 'Inzolia',
       'Petit Verdot', 'Monica', 'Bordeaux-style White Blend', 'Grillo',
       'Sangiovese', 'Cabernet Franc', 'Champagne Blend',
       'Bordeaux-style Red Blend', 'Aglianico', 'Petite Sirah',
       'Touriga Nacional', 'Carmenère', 'Albariño', 'Petit Manseng',
       'Rosé', 'Zinfandel', 'Vernaccia', 'Rosato', 'Grüner Veltliner',
       'Viognier', 'Vermentino', 'Grenache Blanc', 'Syrah', 'Nebbiolo',
       'Shiraz-Cabernet Sauvignon', 'Pinot Blanc', 'Alsace white blend',
       'Barbera', 'Rhône-style Red Blend', 'Portuguese White', 'Graciano',
       'Tannat-Cabernet', 'Sauvignon', 'Sangiovese Grosso', 'Torrontés',
       'Prugnolo Gentile', 'G-S-M', 'Verdejo', 'Fumé Blanc', 'Furmint',
       'Pinot Bianco', 'Bonarda', 'Shiraz', 'Montepulciano', 'Moscato',
       'Grenache', 'Ugni Blanc-Colombard', 'Syrah-Viognier',
       'Blaufränkisch', 'Friulano', 'Assyrtico', 'Carignan-Grenache',
       'Sagrantino', 'Savagnin', 'Cabernet Sauvignon-Syrah', 'Prosecco',
       'Vignoles', 'Sparkling Blend', 'Muscat', 'Muscadelle',
       'Shiraz-Viognier', 'Garganega', 'Pinot Grigio', 'Tempranillo',
       'Zierfandler', 'Cortese', 'Mencía', 'Zweigelt', 'Melon',
       'Rhône-style White Blend', 'Vidal', 'Cannonau', 'Verdelho',
       'Marsanne', 'Scheurebe', 'Kerner', 'Syrah-Grenache', 'Dolcetto',
       'Vilana', 'Glera', 'Viura', 'Garnacha Tintorera', 'Pinot Nero',
       'Roter Veltliner', 'Pinotage', 'Sémillon', 'Pinot Noir-Gamay',
       'Antão Vaz', 'Cabernet Sauvignon-Carmenère', 'Verdejo-Viura',
       'Verduzzo', 'Verdicchio', 'Silvaner', 'Colombard', 'Carricante',
       'Sylvaner', 'Fiano', 'Früburgunder', 'Sousão', 'Roussanne',
       'Avesso', 'Cinsault', 'Chinuri', 'Tinta Miúda',
       'Muscat Blanc à Petits Grains', 'Portuguese Sparkling',
       'Monastrell', 'Xarel-lo', 'Greco', 'Trebbiano',
       'Corvina, Rondinella, Molinara', 'Port', 'Chenin Blanc-Chardonnay',
       'Insolia', 'Merlot-Malbec', 'Ribolla Gialla',
       'Cabernet Sauvignon-Merlot', 'Duras', 'Weissburgunder', 'Roditis',
       'Traminer', 'Papaskarasi', 'Tannat-Syrah', 'Marsanne-Roussanne',
       'Charbono', 'Merlot-Argaman', 'Prié Blanc', 'Sherry',
       'Provence red blend', 'Tannat', 'Zibibbo', 'Falanghina',
       'Garnacha', 'Negroamaro', 'Mourvèdre', 'Syrah-Cabernet',
       'Müller-Thurgau', 'Pinot Meunier', 'Cabernet Sauvignon-Sangiovese',
       'Austrian Red Blend', 'Teroldego', 'Pansa Blanca',
       'Muskat Ottonel', 'Sauvignon Blanc-Semillon', 'Claret',
       'Semillon-Sauvignon Blanc', 'Bical', 'Moscatel', 'Rosado',
       'Viura-Chardonnay', 'Baga', 'Malvasia Bianca',
       'Gelber Muskateller', 'Malbec-Merlot', 'Monastrell-Syrah',
       'Malbec-Tannat', 'Malbec-Cabernet Franc', 'Turbiana', 'Refosco',
       'Alvarinho', 'Manzoni', 'Aragonês', 'Agiorgitiko', 'Malagousia',
       'Assyrtiko', 'Ruché', 'Welschriesling', 'Tinta de Toro',
       'Cabernet Moravia', 'Rieslaner', 'Traminette', 'Chambourcin',
       'Nero di Troia', 'Lambrusco di Sorbara', 'Cesanese',
       'Feteasca Neagra', 'Lagrein', 'Tinta Fina', 'St. Laurent',
       'Marsanne-Viognier', 'Cabernet Sauvignon-Shiraz',
       'Syrah-Cabernet Sauvignon', 'Gewürztraminer-Riesling',
       'Pugnitello', 'Cerceal', 'Touriga Nacional Blend',
       'Austrian white blend', 'Tocai', 'Tinta Roriz',
       'Chardonnay-Viognier', 'Fernão Pires',
       'Cabernet Franc-Cabernet Sauvignon', 'Grenache-Syrah',
       'Seyval Blanc', 'Muscat Canelli', 'Cabernet Merlot',
       'Tempranillo-Cabernet Sauvignon', 'Arinto', 'Aragonez',
       'Merlot-Cabernet Franc', 'Syrah-Petite Sirah', 'Cabernet Blend',
       'Maturana', 'Pecorino', 'Rotgipfler', 'Kinali Yapincak',
       'Cabernet Franc-Carmenère', 'Magliocco', 'Gamay Noir',
       'Sauvignon Gris', 'Spätburgunder', 'Picpoul', 'Vidal Blanc',
       'Albanello', 'White Port', 'Arneis', 'Malvasia', 'Plavac Mali',
       'Lemberger', 'Saperavi', 'Altesse', 'Blanc du Bois',
       'Provence white blend', 'Nosiola', 'Dornfelder',
       'Roussanne-Viognier', 'Ojaleshi', 'Godello', 'Mondeuse',
       'Perricone', 'Pedro Ximénez', 'Auxerrois', 'Syrah-Merlot',
       'Albana', 'Muskat', 'Lambrusco', 'Cabernet Sauvignon-Malbec',
       'Tinto Fino', 'Malbec-Cabernet Sauvignon', 'Moschofilero',
       'Grechetto', 'Encruzado', 'Carignano', 'Cabernet Franc-Merlot',
       'Torbato', 'Syrah-Petit Verdot', 'Garnacha Blanca', 'Pallagrello',
       'Morava', 'Syrah-Mourvèdre', 'Aleatico', 'Carcajolu', 'Kisi',
       'Shiraz-Grenache', 'Palomino', 'Grenache-Carignan', 'Nascetta',
       'Siria', 'Malbec-Syrah', 'Asprinio', 'Feteascǎ Regalǎ',
       'Lambrusco Grasparossa', 'Marselan', 'Tocai Friulano', 'Schiava',
       'Alfrocheiro', 'Chardonnay-Semillon', 'Corvina', 'Norton',
       'Alicante Bouschet', 'Tokaji', 'Moscadello',
       'Cabernet Sauvignon-Tempranillo', 'Carignan', 'Loureiro-Arinto',
       'Cabernet-Syrah', 'Sauvignon Blanc-Chardonnay', 'Symphony',
       'Edelzwicker', 'Madeira Blend', 'Black Muscat', 'Grenache Noir',
       'Durella', 'Xinomavro', 'Tinto del Pais',
       'Merlot-Cabernet Sauvignon', 'Cercial', 'Johannisberg Riesling',
       'Petite Verdot', 'Passerina', 'Valdiguié',
       'Colombard-Sauvignon Blanc', 'Kangoun', 'Loureiro', 'Posip',
       'Uva di Troia', 'Gros and Petit Manseng', 'Jacquère',
       'Kalecik Karasi', 'Karasakiz', 'Mourvèdre-Syrah', 'Negrette',
       'Zierfandler-Rotgipfler', 'Clairette', 'Raboso', 'País', 'Mauzac',
       'Pinot Auxerrois', 'Chenin Blanc-Sauvignon Blanc', 'Diamond',
       'Marzemino', 'Tinta Barroca', 'Chardonnay-Sauvignon Blanc',
       'Castelão', 'Trebbiano Spoletino', 'Teran', 'Trepat', 'Freisa',
       'Neuburger', 'Sämling', 'Chasselas', 'Hárslevelü', 'Trincadeira',
       'Merlot-Tannat', 'Rkatsiteli', 'Melnik', 'Siegerrebe',
       'Trousseau Gris', 'Grenache Blend', 'Gros Manseng',
       'Portuguese Rosé', 'Brachetto', 'Mantonico', 'Ekigaïna',
       'Muskateller', 'Aligoté', 'Sangiovese Cabernet',
       'Touriga Nacional-Cabernet Sauvignon', 'Muscat Blanc', 'Argaman',
       'Viognier-Roussanne', 'Pallagrello Bianco', 'Bobal',
       'Malvasia Istriana', 'Cabernet Sauvignon-Cabernet Franc',
       'Baco Noir', 'Veltliner', 'Tempranillo-Tannat', 'Morillon',
       'Touriga Franca', 'Picolit', 'Barbera-Nebbiolo', 'Prieto Picudo',
       'Gaglioppo', 'Tokay', 'Sacy', 'Piedirosso', 'Piquepoul Blanc',
       'Mansois', 'Chardonnay-Sauvignon', 'Tempranillo-Garnacha',
       'Carmenère-Cabernet Sauvignon', 'Chenin Blanc-Viognier',
       'Susumaniello', 'Vitovska', 'Orange Muscat', 'Grauburgunder',
       'Carignane', 'Moscatel Roxo', 'Tannat-Merlot', 'Nerello Cappuccio',
       'Counoise', 'Macabeo', 'Mazuelo', 'Sauvignon-Sémillon',
       'Tinta del Pais', 'Vranec', 'Mavrud', "Cesanese d'Affile",
       'Moscato Giallo', 'Debit', 'Verdil', 'Cabernet',
       'Verduzzo Friulano ', 'Treixadura', "Loin de l'Oeil",
       'Coda di Volpe', 'Grenache-Mourvèdre', 'Forcallà', 'Viura-Verdejo',
       'Bombino Bianco', 'Pinot-Chardonnay', 'Syrah-Tempranillo',
       'Cabernet Sauvignon-Barbera', 'Merlot-Cabernet',
       "Muscat d'Alexandrie", 'Jaen', 'Tinta del Toro', 'Timorasso',
       'Pigato', 'Sangiovese-Cabernet Sauvignon', 'Shiraz-Cabernet',
       'Viognier-Gewürztraminer', 'Prunelard',
       'Sauvignon Blanc-Chenin Blanc', 'Gros Plant',
       'Malbec-Petit Verdot', 'Colombard-Ugni Blanc', 'Grignolino',
       'Garnacha-Syrah', 'Rufete', 'Tempranillo-Shiraz', 'Mtsvane',
       'Chardonnay-Pinot Gris', 'Marawi', 'Chardonnay-Pinot Blanc',
       'Mataro', 'Tinta Cao', 'Blauer Portugieser', 'Ugni Blanc',
       'Groppello', 'Semillon-Chardonnay', 'Irsai Oliver', 'Alvarelhão',
       'Poulsard', 'Grenache-Shiraz', 'Baga-Touriga Nacional', 'Carineña',
       'Pignoletto', 'Muscatel', 'Mavrodaphne', 'Ciliegiolo',
       'Viognier-Grenache Blanc', 'Greco Bianco',
       'Cabernet Sauvignon-Merlot-Shiraz', 'Sciaccerellu', 'Zelen',
       'Alicante', 'Emir', 'Rosenmuskateller', 'Tsolikouri', 'Narince',
       'Malbec-Cabernet', 'Touriga', 'Grecanico', 'Carmenère-Syrah',
       'Madeleine Angevine', 'Mavroudi', 'Pinot Blanc-Pinot Noir',
       'Muscat Hamburg', 'Tempranillo Blanco', 'Casavecchia',
       'Pinot Gris-Gewürztraminer', 'White Riesling', 'Tinto Velasco',
       'Hondarrabi Zuri', 'Nuragus', 'Xynisteri', 'Kadarka',
       'Sauvignon Musqué', 'Roussanne-Marsanne', 'Incrocio Manzoni',
       'Terrantez', 'Bual', 'Okuzgozu', 'Rivaner', 'Doña Blanca',
       'Graševina', 'Lambrusco Salamino', 'Sangiovese-Syrah',
       'Tannat-Cabernet Franc', 'Thrapsathiri', 'Fer Servadou', 'Mission',
       'Kekfrankos', 'Cococciola', 'Blauburgunder', 'Marquette',
       'Romorantin', 'Verdejo-Sauvignon Blanc', 'Braucol',
       'Malvasia-Viura', 'Savatiano', 'Cabernet Franc-Malbec',
       'Pallagrello Nero', 'Rebula', 'Vespolina', 'Shiraz-Malbec', 'Rebo',
       'Macabeo-Chardonnay', 'Tempranillo-Malbec', 'Tamjanika',
       'Trousseau', 'Bacchus', 'Syrah-Malbec', 'Syrah-Cabernet Franc',
       'Macabeo-Moscatel', 'Cariñena-Garnacha', 'Plyto',
       'Códega do Larinho', 'Sideritis', 'Çalkarası', 'Azal',
       'Moscatel Graúdo', 'Viosinho', 'Moschofilero-Chardonnay',
       'Paralleda', 'Rara Neagra', 'Malvasia di Candia', 'Maria Gomes',
       'Molinara', 'Malvar', 'Airen', 'Erbaluce', 'Muscat of Alexandria',
       'Verdosilla', 'Abouriou', 'Pinot Noir-Syrah', 'Nielluciu',
       'Malbec-Bonarda', 'Vespaiolo', 'Malbec-Carménère', 'Biancolella',
       'Sauvignon Blanc-Verdejo', 'Aidani', 'Garnacha-Monastrell',
       'Vinhão', 'Souzao', 'Roter Traminer', 'Moscatel de Alejandría',
       'Rolle', 'Tinta Francisca', 'Malvasia Nera', 'Orangetraube',
       'Riesling-Chardonnay', 'Žilavka', 'Portuguiser', 'Listán Negro',
       'Pinotage-Merlot', 'Muscadine', 'Maria Gomes-Bical', 'Grolleau',
       'Zlahtina', 'Syrah-Grenache-Viognier', 'Jacquez', 'Gouveio',
       'Canaiolo', 'Carignan-Syrah', 'Bombino Nero',
       'Chardonnay-Riesling', 'Malagouzia-Chardonnay', 'Mavrotragano',
       'Bovale', 'Frankovka', 'Shiraz-Roussanne', 'Cabernet-Shiraz',
       'Syrah-Carignan', 'Elbling', 'Gragnano', 'Garnacha Blend',
       'Pinot Blanc-Chardonnay', 'Schwartzriesling', 'Petit Meslier',
       'Bastardo', 'Vidadillo', 'Misket', 'Chardonnay Weissburgunder',
       'Other', 'Robola', 'Merlot-Shiraz', 'Malagouzia', 'Folle Blanche',
       'Malbec Blend', 'Merlot-Syrah', 'Tamianka', 'Cabernet Pfeffer',
       'Morio Muskat', 'Rabigato', 'Babić', 'Roviello', 'Yapincak',
       'Sauvignonasse', 'Viognier-Marsanne', 'Mandilaria', 'Meseguera',
       'Alvarinho-Chardonnay', 'Saperavi-Merlot', 'Pinot Blanc-Viognier',
       'Teroldego Rotaliano', 'Biancu Gentile', 'Garnacha-Tempranillo',
       'Xinisteri', 'Sauvignon Blanc-Sauvignon Gris',
       'Trebbiano di Lugana', 'Albarossa', 'Ryzlink Rýnský', 'Verdeca',
       'Cabernet Sauvignon Grenache', 'Tămâioasă Românească',
       'Black Monukka', 'Merlot-Grenache', 'Vranac', 'Tempranillo-Syrah',
       'Chardonel', 'Silvaner-Traminer', 'Uvalino',
       'Merseguera-Sauvignon Blanc', 'Cabernet-Malbec', 'Boğazkere',
       'Gelber Traminer', 'Vermentino Nero', 'Cayuga', 'Tinta Amarela',
       'Tinta Negra Mole', 'Moscato Rosa', 'Chelois',
       'Sauvignon Blanc-Assyrtiko', nan, 'Muscadel', 'Shiraz-Tempranillo',
       'Roussanne-Grenache Blanc', 'Biancale', 'Ansonica',
       'Syrah-Bonarda', 'Durif', 'Franconia', 'Malbec-Tempranillo',
       'Nasco', 'Monastrell-Petit Verdot', 'Sirica', 'Vital', 'Espadeiro',
       'Apple', 'Pinot Grigio-Sauvignon Blanc', 'Blatina', 'Karalahna',
       'Feteasca', 'Sercial', 'Valvin Muscat', 'Malvasia Fina',
       'Roditis-Moschofilero', 'St. Vincent', 'Chancellor', 'Premsal',
       'Jampal', 'Tokay Pinot Gris', 'Colorino', 'Picapoll', 'Blauburger',
       'Tinta Madeira', 'Centesimino', 'Grenache Gris', 'Trajadura',
       'Merlot-Petite Verdot', 'Ramisco', 'Catalanesca',
       'Garnacha-Cabernet', 'Garnacha-Cariñena', 'Gamza',
       'Cabernet Franc-Lemberger', 'Chardonnay-Albariño',
       'Shiraz-Mourvèdre', 'Mavrokalavryta', 'Favorita', 'Babosa Negro',
       'Tintilia ', 'Dafni', 'Petit Courbu', 'Kotsifali', 'Parraleta',
       'Moscato di Noto', 'Roscetto', 'Torontel', 'Otskhanuri Sapere',
       'Viognier-Valdiguié', 'Trollinger', 'Tsapournakos', 'Francisa',
       'Kuntra', 'Pignolo', 'Caprettone', 'Ondenc', 'Athiri',
       'Bobal-Cabernet Sauvignon'], dtype=object)

In [13]:
avg = []
for i in grapes:
    avg.append(data[data.variety == i]['points'].mean())

In [14]:
gavg_points = {'Grapes':grapes, 'Average Points': avg} 

gavg_points = pd.DataFrame(gavg_points) 
 
gavg_points = gavg_points.sort_values(by=['Average Points'], ascending=False)
gavg_points

                  Grapes  Average Points
399       Tinta del Pais       95.000000
486            Terrantez       95.000000
633      Gelber Traminer       95.000000
487                 Bual       94.142857
558  Riesling-Chardonnay       94.000000
..                   ...             ...
671             Picapoll       82.000000
643   Shiraz-Tempranillo       82.000000
536                Airen       81.666667
666           Chancellor       80.500000
641                  NaN             NaN

[708 rows x 2 columns]

In [15]:
wine = data['title'].unique()
wine

array(['Nicosia 2013 Vulkà Bianco  (Etna)',
       'Quinta dos Avidagos 2011 Avidagos Red (Douro)',
       'Rainstorm 2013 Pinot Gris (Willamette Valley)', ...,
       'Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)',
       'Domaine Marcel Deiss 2012 Pinot Gris (Alsace)',
       'Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)'],
      dtype=object)

In [16]:
avg = []
for i in wine:
    avg.append(data[data.title == i]['points'].mean())

In [17]:
wine_avg_points = {'Wine':wine, 'Average Points': avg} 

wine_avg_points = pd.DataFrame(wine_avg_points) 
 
wine_avg_points = wine_avg_points.sort_values(by=['Average Points'], ascending=False)
wine_avg_points

                                                     Wine  Average Points
84249   Salon 2006 Le Mesnil Blanc de Blancs Brut Char...           100.0
103443      Château Léoville Las Cases 2010  Saint-Julien           100.0
41019       Casa Ferreirinha 2008 Barca-Velha Red (Douro)           100.0
56012          Château Léoville Barton 2010  Saint-Julien           100.0
113445  Cayuse 2008 Bionic Frog Syrah (Walla Walla Val...           100.0
...                                                   ...             ...
93742   Rooster Hill 2007 Estate Gewürztraminer (Finge...            80.0
93743             McGregor 2006 Pinot Noir (Finger Lakes)            80.0
93744                       Bocage 2006 Merlot (Monterey)            80.0
4537    Fattoria Giuseppe Savini 2011 Rondineto Merlot...            80.0
5871        Cruz Alta 2007 Grand Reserve Malbec (Mendoza)            80.0

[118840 rows x 2 columns]

In [47]:
taster = data['taster_name'].unique()
taster

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [51]:
max_point = []
for i in taster:
    mp = data[data.taster_name == i]['points'].max()
    max_point.append(mp)
max_point

[100,
 100,
 100,
 91,
 98,
 98,
 99,
 97,
 nan,
 97,
 97,
 100,
 97,
 95,
 94,
 97,
 94,
 92,
 91,
 93]

In [52]:
taster_fav = {'Taster name':taster, 'Point': max_point} 
  
# Create DataFrame 
taster_fav = pd.DataFrame(taster_fav) 
  
# Print the output. 
taster_fav = taster_fav.sort_values(by=['Point'], ascending=False)
taster_fav

           Taster name  Point
0        Kerin O’Keefe  100.0
1           Roger Voss  100.0
2         Paul Gregutt  100.0
11      Joe Czerwinski  100.0
6       Virginie Boone   99.0
4    Michael Schachner   98.0
5   Anna Lee C. Iijima   98.0
15        Jeff Jenssen   97.0
12    Anne Krebiehl MW   97.0
10          Jim Gordon   97.0
9     Sean P. Sullivan   97.0
7        Matt Kettmann   97.0
13       Lauren Buzzeo   95.0
14       Mike DeSimone   94.0
16     Susan Kostrzewa   94.0
19   Christina Pickard   93.0
17        Carrie Dykes   92.0
3   Alexander Peartree   91.0
18         Fiona Adams   91.0
8                  NaN    NaN